### ISSUE TITLE
Images on Team Drives

### ISSUE THREAD

**Issue by systemzee** [tanaikech/ImgApp#1]
Seems to not work for images on a team drive.

If I move the image to my drive and run your resize, it works fine. But errors out on the file ID on a team drive.

**Comment by tanaikech** [comment]
I cannot use team drive. I had not been able to implement for the team drive, because I cannot test it. As one workaround,

1. Copy the image file to your Drive.
1. Resize it.
1. Copy the resized image to team drive.

I'm sorry for this situation.

**Comment by systemzee** [comment]
I can create a test team drive and share it to you, then you would have access to a team drive?

thoughts?

**Comment by tanaikech** [comment]
Thank you for your concern. I would like to add it as one of options.

**Comment by tanaikech** [comment]
This has been implemented in version 1.3.2.
