### ISSUE TITLE
Error: '***************' is not compatible file. Error message is {}

### ISSUE THREAD

**Issue by kawa-samurai** [tanaikech/ImgApp#14]
こんちにわ。ImgAppを使わせていただき、GASで開発を行っています。
doResizeを行った時に、以下のようなエラーが出ています。

スクリプト内容
```
function test_resize(){
  var fileId ='***************';
  let res = ImgApp.doResize(fileId, 500);
}
```

エラーメッセージ
> Error: '***************' is not compatible file. Error message is {}
> ImgApp.DoResize @ コード.gs:303
> doResize    @ コード.gs:35

getSizeは問題なく実行でき、対象のファイル形式はJPG形式となっております。
{identification=JPG, filesize=4040889.0, height=3024.0, width=4032.0}

appscript.jsonの内容を
```
{
  "timeZone": "Asia/Tokyo",
  "exceptionLogging": "STACKDRIVER",
  "runtimeVersion": "V8",
  "dependencies": {
    "libraries": [
      {
        "userSymbol": "ImgApp",
        "libraryId": "1T03nYHRho6XMWYcaumClcWr6ble65mAT8OLJqRFJ5lukPVogAN2NDl-y",
        "version": "10"
      }
    ]
  },
  "webapp": {
    "executeAs": "USER_DEPLOYING",
    "access": "ANYONE_ANONYMOUS"
  },
  "oauthScopes": [
    "https://www.googleapis.com/auth/spreadsheets",
    "https://www.googleapis.com/auth/drive.readonly",
    "https://www.googleapis.com/auth/drive",
    "https://www.googleapis.com/auth/script.container.ui"
  ]
}
```

こちらに書き換えると実行ができます。
```
{
  "timeZone": "Asia/Tokyo",
  "exceptionLogging": "STACKDRIVER",
  "runtimeVersion": "V8",
  "dependencies": {
    "libraries": [
      {
        "userSymbol": "ImgApp",
        "libraryId": "1T03nYHRho6XMWYcaumClcWr6ble65mAT8OLJqRFJ5lukPVogAN2NDl-y",
        "version": "10"
      }
    ]
  }
}
```

ただし、他の新規GASスクリプトファイルを作成し、oauthScopesがない状態でもエラーがでます。
複合的な条件だとは思いますが、oauthScopesは必要でして、原因をご調査いただけないでしょうか。

何卒、よろしくお願いいたします。

**Comment by tanaikech** [comment]
いろいろ試していますが、残念ながら、今のところ`Error: '***************' is not compatible file. Error message is {}`のようなエラーを再現することができません。もうしわけありません。可能ですと、再現するためのサンプル画像ファイルを提供していただけないでしょうか。

**Comment by kawa-samurai** [comment]
ご調査いただきありがとうございます。すみません。
今は、動かないことを前提にしてGASを組み立ててしまいました。また、発生しましたらお知らせします。ありがとうござました。

**Comment by tanaikech** [comment]
お役に立てず申し訳ありません。
