### ISSUE TITLE
Can you add an option to set the height of the image instead of width?

### ISSUE THREAD

**Issue by wesselvannierop** [tanaikech/ImgApp#2]
This is particularly useful for vertical images. If this would be possible I would be very grateful.

**Comment by tanaikech** [comment]
Thank you for your comment. In your comment, you want to modify the height but you don't want to modify the width. Is my understanding correct?

**Comment by wesselvannierop** [comment]
Thanks for your quick reply. Excuse me if I was unclear. With your function, doResize, I can input the width for an image to scale it, but keep the same aspect ratio. However, I found out that for vertical images, width (in your function) means the 'longest' side, so the vertical side. This was a bit confusing. But the real problem for me is that I have an maximum length for the horizontal side (of an vertical image). Which with your function would be height. So when I set the width of a 4:3 vertical image it's height will be longer then if I set an 16:9 vertical image with the same width. Therefore I'd like to set It's height to a specific value and scale it accordingly. This way the image fits my boundaries. I'm not very experienced with google script so I can't figure this out myself. Hopefully you'll be able to help. If you still have doubts about my question, I could make some screenshots of my problem with annotations.

**Comment by tanaikech** [comment]
Thank you for replying. I'm really sorry for my poor English skill. I couldn't understand about "vertical images". And unfortunately, I cannot see the vision of your issue. But I can show you the method of resize of this library. You can see the detail information at [here](https://github.com/tanaikech/ImgApp#principle). If this is not useful for your situation, I'm sorry.

**Comment by wesselvannierop** [comment]
I figured it out with basic google script functions, if other people find this, this may be of use:
```javascript
//[...]
//create image with width of 500 and correct aspect ratio
//if it is vertical image this also works (width is always the width)
var newWidth = 500;
//oImg contains the appended image
oImg = oImg.getParent().asParagraph().appendInlineImage(blob);
// Calculate (aspect) ratio
var orgWidth = oImg.getWidth();
var orgHeight = oImg.getHeight();
var ratio = orgHeight/orgWidth;
//Calculate new height for width of 500 and same ratio
var newHeight = newWidth*ratio;
//Set new height and width to image
oImg.setWidth(newWidth).setHeight(newHeight);
```

**Comment by tanaikech** [comment]
I'm glad your issue was solved.
