### ISSUE TITLE
Log Error

### ISSUE THREAD

**Issue by InTheCloudDan** [tanaikech/ImgApp#5]
Would it be possible to make it log the error that it's catching on https://github.com/tanaikech/ImgApp/blob/master/src/ImgApp.coffee#L113-L114

**Comment by tanaikech** [comment]
Thank you for your comment. I updated this library. Please check [https://github.com/tanaikech/ImgApp#update-history](https://github.com/tanaikech/ImgApp#update-history) and [https://github.com/tanaikech/ImgApp/blob/master/src/ImgApp.coffee#L113-L114](https://github.com/tanaikech/ImgApp/blob/master/src/ImgApp.coffee#L113-L114).

**Comment by InTheCloudDan** [comment]
@tanaikech thank you for that, it helped solve the issue I was having!
